### ISSUE TITLE
[Question] Compatiblity with bspatch

### ISSUE THREAD

**Issue by michal-kowalczyk** [divvun/bidiff#10]
I am evaluating bidiff to be used to generate patches for an embedded system.
I found that it is a way faster than any implementation of bsdiff that I've tried so far.
It would be great to use both tools bidiff for generating the patch and bspatch for applying it.
Is there a way to generate a patch that is compatible with bspatch?
If not, is it a planned feature?

**Comment by bbqsrc** [comment]
Nope, sorry.
