### ISSUE TITLE
Mismatch between crates.io and this repo: version and deps

### ISSUE THREAD

**Issue by Terkwood** [divvun/bidiff#8]
Hello,

Thank you for creating this work.  It's proving to be quite handy for making and applying patches!

While experimenting, I noticed that the version of `bidiff` [listed on crates.io](https://crates.io/crates/bidiff) is set to `1.0.0`.

Meanwhile, this repo's `Cargo.toml` shows a version of `0.1.0`.

What's more, there is a slight mismatch in the dependencies, as well: rayon, log, and proptest (dev dep) have slightly higher versions.

Would it be possible to merge the outstanding changes from the crates.io artifact  into this repository's `master` branch?

**Comment by bbqsrc** [comment]
A case of having forgotten to push. fixed!

**Comment by Terkwood** [comment]
Very much appreciated! 

Happy holidays and Happy New Year 🎄 🌟
